before:
  hooks:
    - go mod download
    - go mod tidy
builds:
  - id: rq-darwin
    ldflags:
      - -s -w -X github.com/dotnetmentor/rq/version.Version={{.Version}} -X github.com/dotnetmentor/rq/version.Commit={{.FullCommit}}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
  - id: rq-linux
    ldflags:
      - -s -w -X github.com/dotnetmentor/rq/version.Version={{.Version}} -X github.com/dotnetmentor/rq/version.Commit={{.FullCommit}}
    goos:
      - linux
    goarch:
      - amd64
archives:
  - id: rq-archive
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: darwin
        format: zip
    files:
      - README.md
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - name: rq
    tap:
      owner: dotnetmentor
      name: homebrew-tap
    commit_author:
      name: "Kristoffer Ahl"
    homepage: https://github.com/dotnetmentor/rq
    description: Resource Query cli
    license: Apache License 2.0
    install: |
      bin.install 'rq'
      output = Utils.safe_popen_read("#{bin}/rq", 'completion', 'bash')
      (bash_completion/'rq').write output
      output = Utils.safe_popen_read("#{bin}/rq", 'completion', 'zsh')
      (zsh_completion/'_rq').write output
